Rework/charts rework
WoWs-Builder-Team/WoWs-ShipBuilder pull request #195
Opened 2023-01-19 19:49 UTC by yesod30

Rewrite of charts to make use of ship builds. This solves #194 and also enables acceleration charts for all users, ending the beta period.

2023-02-16 22:21 UTC, iTTou approved these changes

2023-03-03 21:36 UTC, floribe2000 requested changes
Looks good for the most parts, please provide clarification for comments

2023-03-03 21:36 UTC, floribe2000 commented on WoWsShipBuilder.Core/DataContainers/DispersionPlotHelper.cs
>          private static (double waterLineProjection, double perpendicularToWaterProjection, double projectedOnWaterVerticalRadius, double perpendicularToWaterVerticalRadius) GetProjectedEllipse(Artill
Using tuples with that many parameters may justify using a dedicated type for it

2023-03-03 21:36 UTC, floribe2000 commented on WoWsShipBuilder.Web/Components/DispersionPlot.razor
> +                    @dispersionEllipse.Name
Why does the data structure contain localized data? Is this necessary or not?

2023-03-03 21:36 UTC, floribe2000 commented on WoWsShipBuilder.Web/Components/DispersionPlot.razor
> +    public Dictionary<Guid, DispersionEllipse>  Ships { get; set; } = default!;
Don't initialize with "default!" when there is no EditorRequired attribute.
Also check if using ImmutableDictionary may be the right choice here. Ideally, parameters are immutable types

2023-03-03 21:36 UTC, floribe2000 commented on WoWsShipBuilder.Web/Components/ShipStatsComponent.razor
> +    public EventCallback SaveBuildStringIntoLocal { get; set; }
Why a callback?

2023-03-03 21:36 UTC, floribe2000 commented on WoWsShipBuilder.Web/Dialogs/ShipAndShellSelectionDialog.razor
> +                    <ShipSelector SelectedShips="@selectedShips" LargerList AllowCopies/>
Consider adjusting the selector to allow filtering ships that are irrelevant for this dialog (in this case: all ships without main or secondary guns)

2023-03-03 22:34 UTC, floribe2000 approved these changes
LGTM

2023-03-03 22:35 UTC, merged