ShipStats Rework
WoWs-Builder-Team/WoWs-ShipBuilder pull request #199
Opened 2023-02-19 16:14 UTC by iTTou

- Add ability to open multiple builds of the same ship at the same time
- Change chips into shipSelector to proper list
- Ability to assign multiple builds to selected ships before opening stats
- Build string in the home page now accepts also links and short links
- Add build string input dialog with string validation for both links and build strings (short links not supported)
- Add a bunch of missing localizations
- Add build name to shipStats page

2023-03-28 20:16 UTC, floribe2000 requested changes
Overall good changes, however, there are some issues in both code and styling. Please have a look at them.

2023-03-28 20:16 UTC, floribe2000 commented on WoWsShipBuilder.Web/Components/ShipStatsContainer.razor
> +                                <MudStack Class="px-2 cursor-pointer" @onmouseup="@(args => UpdateToShip(args, CurrentTabId, ship))" AlignItems="AlignItems.Center" id="@(ViewModel.CurrentShipIndex +
Use the key property for elements generated in loops

2023-03-28 20:16 UTC, floribe2000 commented on WoWsShipBuilder.Web/Dialogs/BuildStringInputDialog.razor
> +        if (buildString.Contains("build="))
The variable name "buildString" implies that it only contains the unescaped build string

2023-03-28 20:16 UTC, floribe2000 commented on WoWsShipBuilder.Web/Dialogs/BuildStringInputDialog.razor
> +    private string? ValidateBuildString(string buildStr)
Add localization for validation results

2023-03-28 20:16 UTC, floribe2000 commented on WoWsShipBuilder.Web/Dialogs/BuildStringInputDialog.razor
> +        if (buildStr.Contains("share.wowssb.com"))
Do not hardcode urls or hostnames, use data from config file.
Also, why is this not supported? You can retrieve the real url by sending a HTTP request with FollowRedirects disabled

2023-03-28 20:16 UTC, floribe2000 commented on WoWsShipBuilder.Web/Pages/Index.razor
> +        if (buildString.Contains("share.wowssb.com"))
Again, do not hardcode urls or hostnames unless their structure is defined in code in the same project (like the name of a specific page)

2023-03-28 20:16 UTC, floribe2000 commented on WoWsShipBuilder.Web/Pages/ShipStats.razor
> +            var indexes = shipIndexesFromUrl.Split(",").ToList();
Why the .ToList()?

2023-03-29 06:59 UTC, iTTou commented on WoWsShipBuilder.Web/Components/ShipStatsContainer.razor
> +            <MudPaper Outlined="true" Class="py-2 px-15">
After the addition of the text field for the build name the padding wasn't centering the items properly anymore so I had to change it out with that

2023-03-30 18:49 UTC, floribe2000 requested changes
This looks pretty good now, there is just one minor question I had, see the comment. Once this is solved and the merge conflicts are resolved, this can then be merged.

2023-03-30 18:49 UTC, floribe2000 commented on WoWsShipBuilder.Web/Dialogs/BuildStringInputDialog.razor
> +        if (buildStr.Contains(';'))
Why is this check necessary? The try-catch should already catch issues if the string is malformed and there is no longer handling for the old case where there was an url-escaped string

2023-03-30 21:28 UTC, merged