Update 2.0 (Desktop)
WoWs-Builder-Team/WoWs-ShipBuilder pull request #237
Opened 2023-06-11 11:26 UTC by floribe2000

2023-06-11 11:39 UTC, yesod30 approved these changes

2023-06-11 16:08 UTC, iTTou approved these changes
LGTM

2023-06-11 18:10 UTC, iTTou requested changes
UU for venezia and halland are still bugged

2023-06-12 17:35 UTC, iTTou approved these changes
LGTM

2023-06-17 16:54 UTC, merged